language: objective-c
os:
    - osx
    - linux

env:
  global:
    - GOPATH=~

sudo: required

before_install:
    - brew update
    - brew install shellcheck

install:
    - curl -L dot.b4b4r07.com | bash
    - cd $(dotpath); make init

script:
    - make --silent test
