language: c
os:
    - linux
    - osx

env:
  global:
    - GOPATH=~
    - DOTPATH=~/.dotfiles

sudo: required

before_install:
    - curl -L dot.b4b4r07.com | bash
    - cd $(dotpath)
    - make init

install:
    - sudo apt-get install shellcheck

script:
    - make --silent test
