language: c
os:
    - osx
    - linux

env:
  global:
    - GOPATH=~

before_install:
    - sudo apt-get update
    - sudo apt-get install shellcheck

install:
    - curl -L dot.b4b4r07.com | bash
    - cd $(dotpath); make init

script:
    - make --silent test
