language: c
os:
    - osx
    - linux

env:
  global:
    - GOPATH=~

before_install:
    - sudo apt-get install cabal-install
    - cabal update
    - cabal install shellcheck

install:
    - curl -L dot.b4b4r07.com | bash -s init

script:
    - make --silent test
